### ISSUE TITLE
Finalize MVPoly tests generalization

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/proof-systems#2542]
#### Tasks:

- [x] Generalize the `test_homogeneous_eval` tests.
- [x] Generalize the `test_add_monomial` tests.
- [x] Generalize the `test_is_multilinear` tests.
- [x] Get rid of `modify_monomial_with_scalar`.
  - Implement a generic method `modify_monomial` (already implemented for `monomials`), and use it instead.

#### Context:

- https://github.com/o1-labs/proof-systems/pull/2541
